name: 'Upload a Build Artifact'
description: 'Uploads a build artifact, that you can download later'
author: 'kittaakos'
inputs: 
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
